### ISSUE TITLE
Convert colors to :root {...} and callable

### ISSUE THREAD

**Issue by prezine** [CirclepandaLab/pandakit#23]
Save all colors saved in 
```css
:root {
   --color-one : #ffffff;
   ...
}
```
and callable using ```var(--color-one)```
